language: c
sudo: false

arch:
  - amd64
  - ppc64le
  - arm64
  - s390x

compiler:
  - gcc
  - clang

script:
  - ./autogen.sh
  - ./configure
  - make -j$(nproc)
  - vdsotest=./vdsotest ./vdsotest-all
  - make distcheck
